version: "3.8"

services:
  # Backend Nginx
  nginx-backend:
    image: nginx
    container_name: prestabanco-nginx-backend-container
    restart: always
    ports:
      - 8090:8090
    volumes:
      - ./backend.conf:/etc/nginx/nginx.conf
    networks:
      - prestabanco-backend-network 
    depends_on:
      - spring1
      - spring2
      - spring3

  # Frontend Nginx
  nginx-frontend:
    image: nginx
    container_name: prestabanco-frontend-container
    restart: always
    ports:
      - 8070:80
    volumes:
      - ./frontend.conf:/etc/nginx/nginx.conf
    networks:
      - prestabanco-frontend-network
    depends_on:
      - react1
      - react2
      - react3

  # MySQL Database
  mysql:
    container_name: prestabanco-mysql-container
    image: mysql
    restart: on-failure
    volumes:
      - prestabanco-mysql-volume:/var/lib/mysql
    networks:
      - prestabanco-backend-network
    environment:
      MYSQL_ROOT_PASSWORD: N0fum4r4S.
    ports:
      - 3306:3306

  # Backend Spring Boot Services
  spring1:
    container_name: prestabanco-backend-container-1
    image: martiny21/prestabanco-backend
    ports:
      - 8091:8090
    environment:
      DB_HOST: prestabanco-mysql-container
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: N0fum4r4S.
    networks:
      - prestabanco-backend-network
    restart: on-failure
    depends_on:
      - mysql

  spring2:
    container_name: prestabanco-backend-container-2
    image: martiny21/prestabanco-backend
    ports:
      - 8092:8090
    environment:
      DB_HOST: prestabanco-mysql-container
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: N0fum4r4S.
    networks:
      - prestabanco-backend-network
    restart: on-failure
    depends_on:
      - mysql

  spring3:
    container_name: prestabanco-backend-container-3
    image: martiny21/prestabanco-backend
    ports:
      - 8093:8090
    environment:
      DB_HOST: prestabanco-mysql-container
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: N0fum4r4S.
    networks:
      - prestabanco-backend-network
    restart: on-failure
    depends_on:
      - mysql

  # Frontend React Services
  react1:
    container_name: prestabanco-frontend-container-1
    image: martiny21/prestabanco-frontend
    ports:
      - 3001:80
    networks:
      - prestabanco-frontend-network
    restart: on-failure

  react2:
    container_name: prestabanco-frontend-container-2
    image: martiny21/prestabanco-frontend
    ports:
      - 3002:80
    networks:
      - prestabanco-frontend-network
    restart: on-failure

  react3:
    container_name: prestabanco-frontend-container-3
    image: martiny21/prestabanco-frontend
    ports:
      - 3003:80
    networks:
      - prestabanco-frontend-network
    restart: on-failure

volumes:
  prestabanco-mysql-volume:

networks:
  prestabanco-frontend-network:
  prestabanco-backend-network:
