pipeline{
    agent any
    tools{
        maven "maven"

    }
    environment {
        DB_HOST = 'localhost'  // Cambia esto por la IP o nombre del contenedor de la base de datos
        DB_PORT = '3306'  // Cambia esto por el puerto que estés usando para la base de datos
    }
    stages{
        stage("Build JAR File"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/martiny21/Lab1Tingeso']])
                dir("Monolitic project/demo"){
                    bat "mvn clean install"
                }
            }
        }
        stage("Test"){
            steps{
                dir("Monolitic project/demo"){
                    bat "mvn test"
                }
            }
        }        
        stage("Build and Push Docker Image") {
            steps {
                dir("Monolitic project/demo") {
                script {
                    withDockerRegistry(credentialsId: 'docker-credentials'){
                        // build
                        bat "docker build -t martiny21/prestabanco-backend:latest ."
                        // push the image
                        bat "docker push martiny21/prestabanco-backend:latest"
                    }
            }
        }
    }
}

    }
}