pipeline{
    agent any
    tools{
        maven "maven"

    }
    stages{
        stage("Build JAR File"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/martiny21/Lab1Tingeso']])
                dir("Monolitic project/demo"){
                    bat "mvn clean install"
                }
            }
        }
        stage("Test"){
            steps{
                dir("Monolitic project/demo"){
                    bat "mvn test"
                }
            }
        }        
        stage("Build and Push Docker Image") {
            steps {
                dir("Monolitic project/demo") {
                script {
                    withDockerRegistry(credentialsId: 'id-credential'){
                        // build
                        bat "docker build -t martiny21/prestabanco-backend ."
                        // push the image
                        bat "docker push martiny21/prestabanco-backend"
                    }
            }
        }
    }
}

    }
}