pipeline{
    agent any
    tools{
        maven "maven"

    }
    stages{
        stage("Build JAR File"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/martiny21/Lab1Tingeso']])
                dir("demo"){
                    bat "mvn clean install"
                }
            }
        }
        stage("Test"){
            steps{
                dir("demo"){
                    bat "mvn test"
                }
            }
        }        
        stage("Build and Push Docker Image") {
            steps {
                dir("demo") {
                script {
                    // build
                    bat "docker build -t martiny21/prestabanco-backend:latest ."
                    // push the image
                    bat "docker push martiny21/prestabanco-backend:latest"
            }
        }
    }
}

    }
}